Repository version0chiro/Find-Me-Issues, pull requests merged in 2021-10, with the labels that each got.

#44 Revert "README file updated"
  README.md
Labels: hacktoberfest-accepted

#46 README made better
  README.md
  assets/demo1.png
  assets/main_website.PNG
Labels: hactoberfest, hactoberfest-accepted

#48 chore: add more searcheable languages
  client/src/data/languages.json
Labels: hactoberfest, hactoberfest-accepted, hacktoberfest-accepted, hacktoberfest
